apiVersion: v1
kind: Pod
metadata:
  name: application-pod
spec:
  containers:
  - name: app-container
    image: app-img
    ports:
    - containerPort: 3000
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.5"
