apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-container
        image: order-img
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.5"
