apiVersion: v1
kind: Pod
metadata:
  name: order-service-pod
spec:
  containers:
  - name: order-container
    image: order-img
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.5"
