apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-container
        image: products-img
        ports:
        - containerPort: 3030
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.5"
